
  version: '3'

  services:
    db:
      image: mongo:5
      restart: always
      ports:
        - 8000:27018
      environment:
        MONGODB_DATABASE: nest-pokemon
      volumes:
        - ./mongo:/data/db


